# Generated by Django 4.0.1 on 2022-01-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_image_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
