# Generated by Django 4.0.1 on 2022-01-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_image_image_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageMetadata',
        ),
    ]
