# Generated by Django 4.0.1 on 2022-01-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_image_imagemetadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemetadata',
            old_name='url',
            new_name='location',
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='file_type',
            field=models.TextField(default='jpg', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='name',
            field=models.TextField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='size',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
