# Generated by Django 4.0.1 on 2022-01-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_url_imagemetadata_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemetadata',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
