# Generated by Django 4.0.1 on 2022-01-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_alter_imagetags_image_alter_imagetags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='image_hash',
            field=models.TextField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
